### ISSUE TITLE
Ghost tiles that cannot be moved and disappear on reload

### ISSUE THREAD

**Issue by gatopeich** [andstatus/game2048#23]
Before:
![Uploading Screenshot_20240715-182156.png…]()

After:
![Screenshot_20240715-182642](https://github.com/user-attachments/assets/cc5954f6-f318-4004-8fd2-797c26685019)

Not sure if it is a graphic glitch or game state inconsistentcy, because the affected tile disappears if I switch the app e.g. to the browser and back, like happened before I took the 2nd screenshot.

Game export:
[2024-07-14-12-36_10068.game2048.json](https://github.com/user-attachments/files/16237604/2024-07-14-12-36_10068.game2048.json)

**Comment by yvolk** [comment]
Hello @gatopeich 
Thank you for the report. Yes, I also saw such lost tiles sometimes. These are glitches of the game engine that I use, and I couldn't eliminate them so far.
I hope that some upcoming update of the KorGE (game engine) will resolve the problem magically :-)

**Comment by DaBaldEagul** [comment]
Unfortunately these are still here, and are very common. It's practically impossible to play this way...

**Comment by yvolk** [comment]
@gatopeich @DaBaldEagul I published Beta v.1.16.0 to  #1 with possible fix for the "Ghost tiles" bug. Could you check if there is any progress?

**Comment by DaBaldEagul** [comment]
@yvolk they don't seem to be as common (from limited testing), but they definitely still appear. Usage of the undo/redo buttons seems to worsen it. I'd share a screen recording but that restarts the app for some reason.

**Comment by yvolk** [comment]
@DaBaldEagul Thank you for testing and pointing to undo/redo. Video recording is not needed.
Actually even my automatic "unit tests" sometimes failed before the change but now didn't fail after several runs. I will make these tests faster to start seeing the problems again...

For the record: this improvement was due to migration to the newer version 6.0.0 of the game engine ([KorGE](https://korge.org/))
